FROM amazoncorretto:11-alpine-jdk
MAINTAINER JoseNovillo
COPY Backend/target/argentinaprograma-0.0.1-SNAPSHOT portfolioArgentinaPrograma-app.jar
ENTRYPOINT  ["java","-jar","/portfolioArgentinaPrograma-app.jar"]
