FROM amazoncorretto:11-apine-jdk
MAINTAINER JoseNovillo
COPY target/argentinaprograma-0.0.1-SNAPSHOT portfolioArgentinaPrograma-app.jar
ENTRYPOINT  ["java","-jar","/portfolioArgentinaPrograma-app.jar"]
