FROM amazoncorretto:11-alpine-jdk
MAINTAINER JoseNovillo
COPY target/argentinaprograma-0.0.1-SNAPSHOT.jar portfolioArgentinaPrograma-app.jar
ENTRYPOINT  ["java","-jar","/portfolioArgentinaPrograma-app.jar"]
