FROM amazoncorretto:8-alpine-jdk
MAINTAINER JoseNovillo
COPY target/argentinaprograma-0.0.1-SNAPSHOT.jar argentinaprograma-0.0.1-SNAPSHOT.jar
ENTRYPOINT  ["java","-jar","/argentinaprograma-0.0.1-SNAPSHOT.jar"]
WORKDIR D:\Proyectos copiado\TrabajoArgentinaProgramaJose\TrabajoArgentinaPrograma
